{
  "swagger": "2.0",
  "info": {
    "description": "",
    "version": "1.0",
    "title": "FranConnect API",
    "termsOfService": "",
    "contact": {
      "name": "FranConnect"
    }
  },
  "basePath": "/manage-finance",
  "tags": [
    {
      "name": "REST API",
      "description": "<h3 class=\"western\">REST API Overview</h3>\n<p>The Sales module is used to streamline franchisee recruitment process and manage leads. It allows you to create leads, update leads’ details as they move along the franchise recruitment process, and finally award them franchisees.</p>\n>"
    },
    {
      "name": "Authentication",
      "description": "<p class=\"western\">Authentication in the REST API for Finance happens using OAuth 2.0 with grant type as &ldquo;password&rdquo;. In order to generate an access token, the user has to have a valid FCSky login credential. The subsequent steps are as below:</p><p class=\"western\"></p><ol><li><p>The user has to make a &ldquo;POST&rdquo; type request to&nbsp;<span style=\"color: #0563c1;\"><u><a href=\"https://auth.franconnect.net/userauth/oauth/token\">https://auth.franconnect.net/userauth/oauth/token</a></u></span>.</p></li><li><p>The user has to mention his/ her username and password in the &ldquo;username&rdquo; and &ldquo;password&rdquo; parameters and has to specify the &ldquo;grant_type&rdquo; as &ldquo;password&rdquo;. This needs to be passed in the request as parameters and the request has to be posted as &ldquo;form-data&rdquo;.</p></li><li><p>&ldquo;Authorization&rdquo; needs to be set as &ldquo;Basic Auth&rdquo; and the &ldquo;client_id&rdquo; and &ldquo;client_secret&rdquo; keys are to be mentioned as username and password. This is different for each client and can be obtained from FranConnect&rsquo;s Helpdesk, Advocacy, and/ or Client Operations teams.</p></li><li><p>In the body of the request, the user has to mention &ldquo;Content-Type&rdquo; as &ldquo;application/json&rdquo; (or &ldquo;application/xml) and &ldquo;X-TenantId&rdquo; as the user&rsquo;s FranConnect system&rsquo;s login URL prior to &ldquo;/fc&rdquo;.For e.g., in case the FranConnect system&rsquo;s login URL is <span style=\"color: #0563c1;\"><u><a href=\"https://abc.franconnect.net/fc\">https://abc.franconnect.net/fc</a></u></span>, then the user has to specify &ldquo;abc.franconnect.net&rdquo; as the key for &ldquo;X-TenantId&rdquo;.</p></li><li><p>This would generate an access token that would be valid for 12hrs. After this, the token would no longer be valid and user has to regenerate the token.</p></li></ol>"
    },
    {
      "name": "Retrieve Franchise Number",
      "description": "<p class=\"western\">Franchise Number can be retrieved by making a &ldquo;GET&rdquo; type request to the API endpoint.</p><p class=\"western\"></p><p class=\"western\"><strong>Production API Endpoint : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnect.net/common/franchisee\">https://skyapi.franconnect.net/common/franchisee</a></u></span></p><p class=\"western\"><strong>UAT API Endpoint &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnectuat.net/common/franchisee\">https://skyapi.franconnectuat.net/common/franchisee</a></u></span></p><p class=\"western\"><strong>Operation Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong> GET</p><p class=\"western\">&nbsp;</p><p class=\"western\">For this, the user has to:</p><p class=\"western\"></p><ol><li><p>Provide &ldquo;Authorization&rdquo; as the key and the value for that should be in the format &ldquo;Bearer access_token&rdquo;. The access_token is the one that is generated as a part of the authentication and the steps for the same can be found <u><a href=\"#tag/Authentication\">here</a></u>.</p></li><li><p>Specify &ldquo;Content-Type&rdquo; as the key and its value as &ldquo;application/json&rdquo;.</p></li><li><p>Mention &ldquo;X-TenantId&rdquo; as the key and its value based on the user&rsquo;s FranConnect system&rsquo;s URL. Details on how to identify the &ldquo;X-TenantId&rdquo; is mentioned <u><a href=\"#tag/Authentication\">here</a></u>.</p></li></ol><p class=\"western\">This would provide the franchise number and the franchise names of all the locations.</p><p class=\"western\">In case the user would like to retrieve the franchise number for a specific location, this is to be done by making a POST type request to the API endpoint along with:</p><ol><li><p>&ldquo;Authorization&rdquo; as the key and its value as &ldquo;Bearer &lt;access_token&gt;&rdquo; wherein the access_token is the one that is generated as a part of the authentication and the steps for the same can be found <u><a href=\"#tag/Authentication\">here</a></u>.</p></li><li><p>Specify &ldquo;Content-Type&rdquo; as the key and its value as &ldquo;application/json&rdquo;.</p></li><li><p>Mention &ldquo;X-TenantId&rdquo; as the key and its value based on the user&rsquo;s FranConnect system&rsquo;s URL. Details on how to identify the &ldquo;X-TenantId&rdquo; is mentioned <u><a href=\"#tag/Authentication\">here</a></u>.</p></li><li><p>In the body of the request, the filter criteria are to be mentioned.</p></li></ol>"
    },
    {
      "name": "Sales - Lead",
      "description": "A lead is a prospect who has shown interest in acquiring a franchisee location."
    },
    {
      "name": "Sales - Compliance",
      "description": "This section details about the contract and financial agreement associated with the franchise process."
    },
    {
      "name": "Sales - Additional Contacts",
      "description": "This section details about the contact records of a lead."
    },
    {
      "name": "Sales - Call",
      "description": "This section details about the calls that are logged to a lead."
    },
    {
      "name": "Sales - Mail",
      "description": "This section details about the communication between the lead and members of the sales team"
    },
    {
      "name": "Sales - Personal Profile",
      "description": "This section details about the lead’s employment history, finances and other related details."
    },
    {
      "name": "Sales - Sales Qualification",
      "description": "This section provides details about qualification of a prospect who has shown interest in acquiring a franchisee location"
    },
    {
      "name": "Sales - Real Estate",
      "description": "This section details about the Physical location of the desired franchise."
    },
    {
      "name": "Sales - Task",
      "description": "The task form for Franchise Sales provides options for logging and assigning a task to various members of the franchise sales team."
    }
  ],
  "paths": {
    "/dataservices/create": {
      "post": {
        "tags": [
          "Sales - Lead"
        ],
        "summary": "Create",
        "description": "<p class=\"western\">The create endpoint is used to create a new lead in the system. </p><p class=\"western\"><strong>Production API Endpoint : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnect.net/manage-finance/sales/franchiseeNo/%7Bid%7D/reportPeriod\"><context-path>/rest/dataservices/create</a></u></span></p><p class=\"western\"><strong>UAT API Endpoint &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnectuat.net/manage-finance/sales/franchiseeNo/%7Bid%7D/reportPeriod\"><context-path>/rest/dataservices/create</a></u></span></p><p class=\"western\"><strong>Operation Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong>POST</p><p class=\"western\">&nbsp;</p><p class=\"western\">In order to create a lead using the REST API, the user should make a POST request on the context path. The following items should be used as path parameters:</p><ol><li><p>An encrypted secure token as a key. Steps on how a secure token is generated is documented <u><a href=\"#tag/Authentication\">here</a></u>.</p></li><li><p>The module for which the create operation is being performed. In this case, the module to be used is “fs”</u>.</p></li><li><p>The subModule for which the create operation is being performed. A list of all subModules can be retrieved from the “submodule” endpoint mentioned <u><a href=\"#tag/Retrieve-Franchise-Number\">here</a></u>.</p></li><li><p>Response type as XML or JSON, depending on the type of response that is desired</u>.</p></li><li><p class=\"western\">xmlString that would contain the parameters/ details of the request that is to be used to create the lead. In order to determine the parameter names/ schema, a query operation is to be performed with the corresponding module and submodule names and operation as “create”. Details on how the query operation is to be performed is mentioned <u><a href=\"#tag/Retrieve-Franchise-Number\">here.</a></u></li></ol></p>",
        "operationId": "Create_Sales",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "salesFilter",
            "description": "ParameterType:PaymentFilter",
            "required": false,
            "schema": {
              "$ref": "#/definitions/PaymentFilter"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                },
                "example": {
                  "constraints": {
                    "franchiseeNo": {
                      "clause": "EQUAL",
                      "values": [
                        "403951414"
                      ]
                    }
                  },
                  "page": {
                    "pageId": "1",
                    "pageSize": "100"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/NewPaymentFilter"
            }
          },
          "201": {
            "description": "Created"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
      "/dataservices/retrieve": {
      "post": {
        "tags": [
          "Sales - Lead"
        ],
        "summary": "Retrieve",
        "description": "<p class=\"western\">The retrieve endpoint is used to retrieve the “Primary Info” for existing leads. </p><p class=\"western\"><strong>Production API Endpoint : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnect.net/manage-finance/sales/franchiseeNo/%7Bid%7D/reportPeriod\"><context-path>/rest/dataservices/retrieve</a></u></span></p><p class=\"western\"><strong>UAT API Endpoint &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnectuat.net/manage-finance/sales/franchiseeNo/%7Bid%7D/reportPeriod\"><context-path>/rest/dataservices/retrieve</a></u></span></p><p class=\"western\"><strong>Operation Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong>POST</p><p class=\"western\">&nbsp;</p><p class=\"western\">In order to retrieve a lead using the REST API, the user should make a POST request on the context path. The following items should be used as path parameters:</p><ol><li><p>An encrypted secure token as a key. Steps on how a secure token is generated is documented <u><a href=\"#tag/Authentication\">here</a></u>.</p></li><li><p>The module for which the retrieve operation is being performed. In this case, the module to be used is “fs”</u>.</p></li><li><p>The subModule for which the retrieve operation is being performed. A list of all subModules can be retrieved from the “submodule” endpoint mentioned <u><a href=\"#tag/Retrieve-Franchise-Number\">here</a></u>.</p></li><li><p>Response type as XML or JSON, depending on the type of response that is desired</u>.</p></li></ol><ol><li><p class=\"western\">filterXml that would contain the parameters/ details of the request that is to be used to retrieve the lead. In order to determine the parameter names/ schema, a query operation is to be performed with the corresponding module and submodule names and operation as “retrieve”. Details on how the query operation is to be performed is mentioned <u><a href=\"#tag/Retrieve-Franchise-Number\">here</a></u>.</li>.</ol></p>",
        "operationId": "Retrieve_Finance_Categories",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ParameterType:Integer",
            "required": false,
            "type": "integer",
            "format": "int32",
            "enum": [
              "Integer"
            ]
          },
          {
            "name": "reportPeriod",
            "in": "path",
            "description": "ParameterType:String",
            "required": false,
            "type": "string",
            "enum": [
              "String"
            ]
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/financeCategories"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
     "/dataservices/update": {
         "post": {
        "tags": [
          "Sales - Lead"
        ],
        "summary": "Update",
        "description": "<p class=\"western\">The update endpoint is used to update the “Primary Info” for existing leads. </p><p class=\"western\"><strong>Production API Endpoint : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnect.net/manage-finance/sales/franchiseeNo/%7Bid%7D/reportPeriod\"><context-path>/rest/dataservices/update</a></u></span></p><p class=\"western\"><strong>UAT API Endpoint &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnectuat.net/manage-finance/sales/franchiseeNo/%7Bid%7D/reportPeriod\"><context-path>/rest/dataservices/update</a></u></span></p><p class=\"western\"><strong>Operation Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong>POST</p><p class=\"western\">&nbsp;</p><p class=\"western\">In order to update a lead using the REST API, the user should make a POST request on the context path. The following items should be used as path parameters:</p><ol><li><p>An encrypted secure token as a key. Steps on how a secure token is generated is documented <u><a href=\"#tag/Authentication\">here</a></u>.</p></li><li><p>The module for which the update operation is being performed. In this case, the module to be used is “fs”</u>.</p></li><li><p>The subModule for which the update operation is being performed. A list of all subModules can be retrieved from the “submodule” endpoint mentioned <u><a href=\"#tag/Retrieve-Franchise-Number\">here</a></u>.</p></li><li><p>Response type as XML or JSON, depending on the type of response that is desired</u>.</p></li></ol><ol><li><p class=\"western\">xmlString that would contain the parameters/ details of the request that is to be used to update the lead. In order to determine the parameter names/ schema, a query operation is to be performed with the corresponding module and submodule names and operation as “update”. Details on how the query operation is to be performed is mentioned <u><a href=\"#tag/Retrieve-Franchise-Number\">here</a></u>.</li></ol></p>",
        "operationId": "Retrieve_Non-Finance_Categories",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ParameterType:Integer",
            "required": false,
            "type": "integer",
            "format": "int32",
            "enum": [
              "Integer"
            ]
          },
          {
            "name": "reportPeriod",
            "in": "path",
            "description": "ParameterType:String",
            "required": false,
            "type": "string",
            "enum": [
              "String"
            ]
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/kpicategories"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
        "/dataservices/delete": {
      "post": {
        "tags": [
          "Sales - Lead"
        ],
        "summary": "Delete",
        "description": "<p class=\"western\">The delete endpoint is used to delete leads from the system. </p><p class=\"western\"><strong>Production API Endpoint : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnect.net/manage-finance/sales/franchiseeNo/%7Bid%7D/reportPeriod\"><context-path>/rest/dataservices/delete</a></u></span></p><p class=\"western\"><strong>UAT API Endpoint &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnectuat.net/manage-finance/sales/franchiseeNo/%7Bid%7D/reportPeriod\"><context-path>/rest/dataservices/delete</a></u></span></p><p class=\"western\"><strong>Operation Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong>POST</p><p class=\"western\">&nbsp;</p><p class=\"western\">In order to delete a lead using the REST API, the user should make a POST request on the context path. The following items should be used as path parameters:</p><ol><li><p>An encrypted secure token as a key. Steps on how a secure token is generated is documented <u><a href=\"#tag/Authentication\">here</a></u>.</p></li><li><p>The module for which the delete operation is being performed. In this case, the module to be used is “fs”</u>.</p></li><li><p>The subModule for which the delete operation is being performed. A list of all subModules can be retrieved from the “submodule” endpoint mentioned <u><a href=\"#tag/Retrieve-Franchise-Number\">here</a></u>.</p></li><li><p>Response type as XML or JSON, depending on the type of response that is desired.</u>.</p></li></ol><ol><li><p class=\"western\">filterXml that would contain the parameters/ details of the request that is to be used to delete the lead. In order to determine the parameter names/ schema, a query operation is to be performed with the corresponding module and submodule names and operation as “delete”. Details on how the query operation is to be performed is mentioned <u><a href=\"#tag/Retrieve-Franchise-Number\">here</a></u>.</li></ol></p>",
        "operationId": "Retrieve_Non-Finance_Categories",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ParameterType:Integer",
            "required": false,
            "type": "integer",
            "format": "int32",
            "enum": [
              "Integer"
            ]
          },
          {
            "name": "reportPeriod",
            "in": "path",
            "description": "ParameterType:String",
            "required": false,
            "type": "string",
            "enum": [
              "String"
            ]
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/kpicategories"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
     "/dataservices/compliance": {
      "post": {
        "tags": [
          "Sales - Compliance"
        ],
        "summary": "Create",
        "description": "<p class=\"western\">The create endpoint is used to add Sales Compliance data in the system. </p><p class=\"western\"><strong>Production API Endpoint : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnect.net/manage-finance/sales/franchiseeNo/%7Bid%7D/reportPeriod\"><context-path>/rest/dataservices/create</a></u></span></p><p class=\"western\"><strong>UAT API Endpoint &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnectuat.net/manage-finance/sales/franchiseeNo/%7Bid%7D/reportPeriod\"><context-path>/rest/dataservices/create</a></u></span></p><p class=\"western\"><strong>Operation Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong>POST</p><p class=\"western\">&nbsp;</p><p class=\"western\">In order to add Sales Compliance data using the REST API, the user should make a POST request on the context path. The following items should be used as path parameters:</p><ol><li><p>An encrypted secure token as a key. Steps on how a secure token is generated is documented <u><a href=\"#tag/Authentication\">here</a></u>.</p></li><li><p>The module for which the create operation is being performed. In this case, the module to be used is “fs”</u>.</p></li><li><p>The subModule for which the create operation is being performed. A list of all subModules can be retrieved from the “submodule” endpoint mentioned <u><a href=\"#tag/Retrieve-Franchise-Number\">here</a></u>.</p></li><li><p>Response type as XML or JSON, depending on the type of response that is desired</u>.</p></li><li><p class=\"western\">xmlString that would contain the parameters/ details of the request that is to be used to add Sales Compliance data. In order to determine the parameter names/ schema, a query operation is to be performed with the corresponding module and submodule names and operation as “create”. Details on how the query operation is to be performed is mentioned <u><a href=\"#tag/Retrieve-Franchise-Number\">here.</a></u></li></ol></p>",
        "operationId": "Create_Sales",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "salesFilter",
            "description": "ParameterType:PaymentFilter",
            "required": false,
            "schema": {
              "$ref": "#/definitions/PaymentFilter"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                },
                "example": {
                  "constraints": {
                    "franchiseeNo": {
                      "clause": "EQUAL",
                      "values": [
                        "403951414"
                      ]
                    }
                  },
                  "page": {
                    "pageId": "1",
                    "pageSize": "100"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/NewPaymentFilter"
            }
          },
          "201": {
            "description": "Created"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
      "/dataservices/Compliance retrieve": {
      "post": {
        "tags": [
          "Sales - Lead"
        ],
        "summary": "Retrieve",
        "description": "<p class=\"western\">The retrieve endpoint is used to retrieve the Sales Compliance data. </p><p class=\"western\"><strong>Production API Endpoint : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnect.net/manage-finance/sales/franchiseeNo/%7Bid%7D/reportPeriod\"><context-path>/rest/dataservices/retrieve</a></u></span></p><p class=\"western\"><strong>UAT API Endpoint &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnectuat.net/manage-finance/sales/franchiseeNo/%7Bid%7D/reportPeriod\"><context-path>/rest/dataservices/retrieve</a></u></span></p><p class=\"western\"><strong>Operation Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong>POST</p><p class=\"western\">&nbsp;</p><p class=\"western\">In order to retrieve Sales Compliance data using the REST API, the user should make a POST request on the context path. The following items should be used as path parameters:</p><ol><li><p>An encrypted secure token as a key. Steps on how a secure token is generated is documented <u><a href=\"#tag/Authentication\">here</a></u>.</p></li><li><p>The module for which the retrieve operation is being performed. In this case, the module to be used is “fs”</u>.</p></li><li><p>The subModule for which the retrieve operation is being performed. A list of all subModules can be retrieved from the “submodule” endpoint mentioned <u><a href=\"#tag/Retrieve-Franchise-Number\">here</a></u>.</p></li><li><p>Response type as XML or JSON, depending on the type of response that is desired</u>.</p></li></ol><ol><li><p class=\"western\">filterXml that would contain the parameters/ details of the request that is to be used to retrieve the Sales Compliance data. In order to determine the parameter names/ schema, a query operation is to be performed with the corresponding module and submodule names and operation as “retrieve”. Details on how the query operation is to be performed is mentioned <u><a href=\"#tag/Retrieve-Franchise-Number\">here</a></u>.</li>.</ol></p>",
        "operationId": "Retrieve_Finance_Categories",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ParameterType:Integer",
            "required": false,
            "type": "integer",
            "format": "int32",
            "enum": [
              "Integer"
            ]
          },
          {
            "name": "reportPeriod",
            "in": "path",
            "description": "ParameterType:String",
            "required": false,
            "type": "string",
            "enum": [
              "String"
            ]
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/financeCategories"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
     "/dataservices/update Compliance": {
         "post": {
        "tags": [
          "Sales - Lead"
        ],
        "summary": "Update",
        "description": "<p class=\"western\">The update endpoint is used to update the Sales Compliance data. </p><p class=\"western\"><strong>Production API Endpoint : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnect.net/manage-finance/sales/franchiseeNo/%7Bid%7D/reportPeriod\"><context-path>/rest/dataservices/update</a></u></span></p><p class=\"western\"><strong>UAT API Endpoint &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnectuat.net/manage-finance/sales/franchiseeNo/%7Bid%7D/reportPeriod\"><context-path>/rest/dataservices/update</a></u></span></p><p class=\"western\"><strong>Operation Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong>POST</p><p class=\"western\">&nbsp;</p><p class=\"western\">In order to update the Sales Compliance data using the REST API, the user should make a POST request on the context path. The following items should be used as path parameters:</p><ol><li><p>An encrypted secure token as a key. Steps on how a secure token is generated is documented <u><a href=\"#tag/Authentication\">here</a></u>.</p></li><li><p>The module for which the update operation is being performed. In this case, the module to be used is “fs”</u>.</p></li><li><p>The subModule for which the update operation is being performed. A list of all subModules can be retrieved from the “submodule” endpoint mentioned <u><a href=\"#tag/Retrieve-Franchise-Number\">here</a></u>.</p></li><li><p>Response type as XML or JSON, depending on the type of response that is desired</u>.</p></li></ol><ol><li><p class=\"western\">xmlString that would contain the parameters/ details of the request that is to be used to update the Sales Compliance data. In order to determine the parameter names/ schema, a query operation is to be performed with the corresponding module and submodule names and operation as “update”. Details on how the query operation is to be performed is mentioned <u><a href=\"#tag/Retrieve-Franchise-Number\">here</a></u>.</li></ol></p>",
        "operationId": "Retrieve_Non-Finance_Categories",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ParameterType:Integer",
            "required": false,
            "type": "integer",
            "format": "int32",
            "enum": [
              "Integer"
            ]
          },
          {
            "name": "reportPeriod",
            "in": "path",
            "description": "ParameterType:String",
            "required": false,
            "type": "string",
            "enum": [
              "String"
            ]
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/kpicategories"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
        "/dataservices/delete Compliance": {
      "post": {
        "tags": [
          "Sales - Compliance"
        ],
        "summary": "Delete",
        "description": "<p class=\"western\">The delete endpoint is used to delete Sales Compliance data from the system. </p><p class=\"western\"><strong>Production API Endpoint : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnect.net/manage-finance/sales/franchiseeNo/%7Bid%7D/reportPeriod\"><context-path>/rest/dataservices/delete</a></u></span></p><p class=\"western\"><strong>UAT API Endpoint &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnectuat.net/manage-finance/sales/franchiseeNo/%7Bid%7D/reportPeriod\"><context-path>/rest/dataservices/delete</a></u></span></p><p class=\"western\"><strong>Operation Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong>POST</p><p class=\"western\">&nbsp;</p><p class=\"western\">In order to delete Sales Compliance data using the REST API, the user should make a POST request on the context path. The following items should be used as path parameters:</p><ol><li><p>An encrypted secure token as a key. Steps on how a secure token is generated is documented <u><a href=\"#tag/Authentication\">here</a></u>.</p></li><li><p>The module for which the delete operation is being performed. In this case, the module to be used is “fs”</u>.</p></li><li><p>The subModule for which the delete operation is being performed. A list of all subModules can be retrieved from the “submodule” endpoint mentioned <u><a href=\"#tag/Retrieve-Franchise-Number\">here</a></u>.</p></li><li><p>Response type as XML or JSON, depending on the type of response that is desired.</u>.</p></li></ol><ol><li><p class=\"western\">filterXml that would contain the parameters/ details of the request that is to be used to delete the Sales Compliance data. In order to determine the parameter names/ schema, a query operation is to be performed with the corresponding module and submodule names and operation as “delete”. Details on how the query operation is to be performed is mentioned <u><a href=\"#tag/Retrieve-Franchise-Number\">here</a></u>.</li></ol></p>",
        "operationId": "Retrieve_Non-Finance_Categories",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ParameterType:Integer",
            "required": false,
            "type": "integer",
            "format": "int32",
            "enum": [
              "Integer"
            ]
          },
          {
            "name": "reportPeriod",
            "in": "path",
            "description": "ParameterType:String",
            "required": false,
            "type": "string",
            "enum": [
              "String"
            ]
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/kpicategories"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
     "/royalties/filter": {
      "post": {
        "tags": [
          "Finance - Royalties"
        ],
        "summary": "Retrieve Royalty Invoices",
        "description": "<p class=\"western\">Royalty reports are generated on the basis of sales submitted for the locations and can be retrieved in a similar way as retrieving a sales report. To retrieve a royalty report, a POST type of request is to be made to the specified endpoint.</p><p class=\"western\"><strong>Production API Endpoint : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnect.net/manage-finance/royalties/filter\">https://skyapi.franconnect.net/manage-finance/royalties/filter</a></u></span></p><p class=\"western\"><strong>UAT API Endpoint &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong><span style=\"color: #0563c1;\"><u><a href=\"https://skyapi.franconnectuat.net/manage-finance/royalties/filter\">https://skyapi.franconnectuat.net/manage-finance/royalties/filter</a></u></span></p><p class=\"western\"><strong>Operation Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : </strong> POST</p><p class=\"western\">&nbsp;</p><p class=\"western\">Other details that are to be included in the request are:</p><ol><li><p>&ldquo;Authorization&rdquo; as the key name with its value as &ldquo;Bearer &lt;acess_token&gt;&rdquo;. Steps to retrieve the access_token is mentioned <u><a href=\"#tag/Authentication\">here</a></u>.</p></li><li><p>&ldquo;Content-Type&rdquo; as the key and its value as &ldquo;application/json&rdquo;.</p></li><li><p>&ldquo;X-TenantId&rdquo; as the key and its value as per the FranConnect system&rsquo;s login URL. Steps to determine the &ldquo;X-TenantId&rdquo; is mentioned <u><a href=\"#tag/Authentication\">here</a></u>.</p></li><li><p>The body of the request should contain the constraints that would be used to filter out the royalty invoice(s).</p></li></ol><p class=\"western\">Here is a list of all the attributes that can be used as constraints while retrieving royalty reports along with the &ldquo;clauses&rdquo; that are supported for each constraint.</p><p class=\"western\">&nbsp;</p><center><table width=\"735\" cellspacing=\"0\" cellpadding=\"7\"><colgroup><col width=\"134\" /> <col width=\"253\" /> <col width=\"223\" /> <col width=\"66\" /> </colgroup><tbody><tr valign=\"top\"><td style=\"background: #4472c4;\" bgcolor=\"#4472c4\" width=\"134\" height=\"30\"><p class=\"western\"><span style=\"color: #ffffff;\"><strong>Field</strong></span></p></td><td style=\"background: #4472c4;\" bgcolor=\"#4472c4\" width=\"253\"><p class=\"western\"><span style=\"color: #ffffff;\"><strong>Field Display Name</strong></span></p></td><td style=\"background: #4472c4;\" bgcolor=\"#4472c4\" width=\"223\"><p class=\"western\"><span style=\"color: #ffffff;\"><strong>Applicable Clauses</strong></span></p></td><td style=\"background: #4472c4;\" bgcolor=\"#4472c4\" width=\"66\"><p class=\"western\"><span style=\"color: #ffffff;\"><strong>Format</strong></span></p></td></tr><tr valign=\"top\"><td style=\"background: #d9e2f3;\" bgcolor=\"#d9e2f3\" width=\"134\"><p class=\"western\"><strong>franchiseRoyaltyID</strong></p></td><td style=\"background: #d9e2f3;\" bgcolor=\"#d9e2f3\" width=\"253\"><p class=\"western\">Internal Unique Reference Number of the Royalty Invoicce</p></td><td style=\"background: #d9e2f3;\" bgcolor=\"#d9e2f3\" width=\"223\"><p class=\"western\">EQUAL, IN</p></td><td style=\"background: #d9e2f3;\" bgcolor=\"#d9e2f3\" width=\"66\"><p class=\"western\">String</p></td></tr><tr valign=\"top\"><td width=\"134\" height=\"9\"><p class=\"western\"><strong>invoiceNO</strong></p></td><td width=\"253\"><p class=\"western\">Royalty Invoice Number as seen in UI</p></td><td width=\"223\"><p class=\"western\">EQUAL, IN</p></td><td width=\"66\"><p class=\"western\">String</p></td></tr><tr valign=\"top\"><td style=\"background: #d9e2f3;\" bgcolor=\"#d9e2f3\" width=\"134\"><p class=\"western\"><strong>franchiseeNo</strong></p></td><td style=\"background: #d9e2f3;\" bgcolor=\"#d9e2f3\" width=\"253\"><p class=\"western\">Internal Unique Reference Number of the location</p></td><td style=\"background: #d9e2f3;\" bgcolor=\"#d9e2f3\" width=\"223\"><p class=\"western\">EQUAL, IN</p></td><td style=\"background: #d9e2f3;\" bgcolor=\"#d9e2f3\" width=\"66\"><p class=\"western\">String</p></td></tr><tr valign=\"top\"><td width=\"134\" height=\"85\"><p class=\"western\"><strong>invoiceDate</strong></p></td><td width=\"253\"><p class=\"western\">Invoice Date</p></td><td width=\"223\"><p class=\"western\">EQUAL, GREATER_THAN,</p><p class=\"western\">LESS_THAN, GREATER_THAN_OR_EQUAL,</p><p class=\"western\">LESS_THAN_OR_EQUAL, BETWEEN</p></td><td width=\"66\"><p class=\"western\">Date</p></td></tr><tr valign=\"top\"><td style=\"background: #d9e2f3;\" bgcolor=\"#d9e2f3\" width=\"134\"><p class=\"western\"><strong>paymentStatus</strong></p></td><td style=\"background: #d9e2f3;\" bgcolor=\"#d9e2f3\" width=\"253\"><p class=\"western\">Payment Status</p></td><td style=\"background: #d9e2f3;\" bgcolor=\"#d9e2f3\" width=\"223\"><p class=\"western\">EQUAL, IN</p></td><td style=\"background: #d9e2f3;\" bgcolor=\"#d9e2f3\" width=\"66\"><p class=\"western\">String</p></td></tr></tbody></table></center><p class=\"western\">&nbsp;</p>",
        "operationId": "Retrieve_Royalty_Invoices",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "salesFilter",
            "description": "ParameterType:PaymentFilter",
            "required": false,
            "schema": {
              "$ref": "#/definitions/RoyaltyFilter"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                },
                "example": {
                  "constraints": {
                    "franchiseeNo": {
                      "clause": "EQUAL",
                      "values": [
                        "403951414"
                      ]
                    }
                  },
                  "page": {
                    "pageId": "1",
                    "pageSize": "100"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/financeCategories"
            }
          },
          "201": {
            "description": "Created"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    }
    },
  "definitions": {
    "Character": {
      "type": "object",
      "title": "Character"
    },
    "FilterConstraint": {
      "type": "object",
      "title": "FilterConstraint",
      "description": "This model is used for filter-contraints having field operation and values "
    },
    "Map«string,List«Map«string,object»»»": {
      "type": "object",
      "title": "Map«string,List«Map«string,object»»»",
      "additionalProperties": {
        "$ref": "#/definitions/List"
      }
    },
    "Map«string,object»": {
      "type": "object",
      "title": "Map«string,object»",
      "additionalProperties": {
        "type": "object"
      }
    },
    "Map«string,string»": {
      "type": "object",
      "title": "Map«string,string»",
      "additionalProperties": {
        "type": "string"
      }
    },
    "Page": {},
    "PaymentFilter": {},
    "ProfitLossFilter": {},
    "Response«Result«List«List«Map«string,string»»»»»": {},
    "Response«Result«List«Map«string,List«Map«string,object»»»»»»": {},
    "Response«Result«List«Map«string,object»»»»": {
      "type": "object",
      "properties": {
        "response": {
          "$ref": "#/definitions/Result«List«Map«string,object»»»"
        }
      },
      "title": "Response«Result«List«Map«string,object»»»»"
    },
    "Result«List«List«Map«string,string»»»»": {},
    "List": {},
    "Result«List«Map«string,List«Map«string,object»»»»»": {},
    "Result«List«Map«string,object»»»": {},
    "RoyaltyFilter": {},
    "SalesFilter": {},
    "Sort": {
      "type": "object",
      "properties": {
        "columns": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "direction": {
          "type": "string",
          "enum": [
            "ASC",
            "DESC"
          ]
        }
      },
      "title": "Sort"
    },
    "NewPaymentFilter": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      },
      "example": {
        "response": {
          "data": [
            {
              "298031988": {
                "paymentMappingId": "298031988",
                "paymentID": "1708095951",
                "franchiseRoyaltyId": "1928694199",
                "invoiceNo": "6",
                "paymentNo": "1",
                "amountApplied": "35.00",
                "dateApplied": "2019-06-26 08:32:12",
                "franchiseeNo": "403951414",
                "parentId": null,
                "royaltyType": "All",
                "dateReceived": "2019-06-26",
                "collectionMethod": "Cash",
                "refNo": "",
                "submitDate": "2019-06-26 08:32:11",
                "openBalance": "0.0",
                "memo": "test"
              },
              "497802296": {
                "paymentMappingId": "497802296",
                "paymentID": "1708095951",
                "franchiseRoyaltyId": "1928694199",
                "invoiceNo": "6",
                "paymentNo": "1",
                "amountApplied": "350.00",
                "dateApplied": "2019-06-26 08:32:11",
                "franchiseeNo": "403951414",
                "parentId": null,
                "royaltyType": "All",
                "dateReceived": "2019-06-26",
                "collectionMethod": "--",
                "refNo": "",
                "submitDate": "2019-06-26 08:32:11",
                "openBalance": "0.0",
                "memo": "test"
              },
              "732473447": {
                "paymentMappingId": "732473447",
                "paymentID": "1708095951",
                "franchiseRoyaltyId": "1928694199",
                "invoiceNo": "6",
                "paymentNo": "1",
                "amountApplied": "215.0",
                "dateApplied": "2019-06-26 08:32:12",
                "franchiseeNo": "403951414",
                "parentId": null,
                "royaltyType": "All",
                "dateReceived": "2019-06-26",
                "collectionMethod": "--",
                "refNo": "",
                "submitDate": "2019-06-26 08:32:11",
                "openBalance": "0.0",
                "memo": "test"
              },
              "response": "Success"
            }
          ],
          "page": null
        }
      }
    },
    "createSales": {},
    "salesRetrieve": {},
    "salesUpdate": {},
    "financeCategories": {},
    "kpicategories": {},
    "additionalLineItems": {},
    "salesReportPeriod": {},
    "salesStatus": {},
    "salesReportType": {}
  }
}
